name: my_books
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.2

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  flutter_bloc: ^8.1.1
  firebase_core: ^2.3.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.2.1
  intl: ^0.18.0
  dio: ^5.1.2
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  retrofit: ^4.0.1
  get_it: ^7.2.0
  injectable: ^2.1.1
  firebase_ui_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  retrofit_generator: ^7.0.1
  injectable_generator: ^2.1.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
