name: my_books
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  flutter_bloc: ^8.1.1
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  flutterfire_ui: ^0.4.3+20
  firebase_auth: ^4.2.1
  intl: ^0.17.0
  dio: ^4.0.6
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  retrofit: ^3.3.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
